name: Deploy Production Theme

on:
  push:
    pull_request: null
    branches:
      - master

jobs:
  deploy:
    name: Deploy Production Theme
    runs-on: ubuntu-latest
    steps:
      # basically git clone
      - uses: actions/checkout@v2
      # deploy shopify theme
      - uses: pgrimaud/action-shopify@2.1.0
steps:
      - uses: actions/checkout@v1
      - name: Shopify
        uses: pgrimaud/action-shopify@master
        env:
          SHOPIFY_PASSWORD: ${{ secrets.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 }}
          SHOPIFY_STORE_URL: ${{ secrets.ap-demo-dhivya.myshopify.com }}
          SHOPIFY_THEME_ID: ${{ secrets.102140379293 }}
          THEME_PATH: ${{ secrets../. }}
        with:
          args: --ignored-file=config/settings_data.json --ignored-file=locales/*
